baseURL = 'https://momarfarooq.github.io/generative-ai-lecture-2026/'
languageCode = 'en-us'
title = 'Generative AI Lecture'
theme = 'ananke'
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
